pipeline {
  agent any

  environment {
    AWS_ACCESS_KEY_ID     = credentials('aws-creds')
    AWS_SECRET_ACCESS_KEY = credentials('aws-creds')
    AWS_DEFAULT_REGION    = 'eu-west-2'
  }

  stages {
    stage('Init') {
      steps {
        dir('terraform') {
          sh 'terraform init'
        }
      }
    }

    stage('Apply Infra') {
      steps {
        dir('terraform') {
          sh 'terraform apply -auto-approve'
        }
      }
    }

    stage('Configure kubectl') {
      steps {
        sh '''
          aws eks update-kubeconfig --region eu-west-2 --name super-mario-eks
        '''
      }
    }

    stage('Deploy App') {
      steps {
        sh '''
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
        '''
      }
    }
  }
}

