apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-mario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-mario
  template:
    metadata:
      labels:
        app: super-mario
    spec:
      containers:
        - name: super-mario
          image: alexwhen/docker-supermario
          ports:
            - containerPort: 8080
